package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1558</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_ungrab_key_request_t extends Structure {
	/** < */
	public byte major_opcode;
	/**
	 * <<br>
	 * C type : xcb_keycode_t
	 */
	public byte key;
	/** < */
	public short length;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int grab_window;
	/** < */
	public short modifiers;
	/**
	 * <<br>
	 * C type : uint8_t[2]
	 */
	public byte[] pad0 = new byte[2];
	public xcb_ungrab_key_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("major_opcode", "key", "length", "grab_window", "modifiers", "pad0");
	}
	/**
	 * @param major_opcode <<br>
	 * @param key <<br>
	 * C type : xcb_keycode_t<br>
	 * @param length <<br>
	 * @param grab_window <<br>
	 * C type : xcb_window_t<br>
	 * @param modifiers <<br>
	 * @param pad0 <<br>
	 * C type : uint8_t[2]
	 */
	public xcb_ungrab_key_request_t(byte major_opcode, byte key, short length, int grab_window, short modifiers, byte pad0[]) {
		super();
		this.major_opcode = major_opcode;
		this.key = key;
		this.length = length;
		this.grab_window = grab_window;
		this.modifiers = modifiers;
		if ((pad0.length != this.pad0.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad0 = pad0;
	}
	public xcb_ungrab_key_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_ungrab_key_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_ungrab_key_request_t implements Structure.ByValue {
		
	};
}
