package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:2447</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_get_image_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte depth;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/**
	 * <<br>
	 * C type : xcb_visualid_t
	 */
	public int visual;
	/**
	 * <<br>
	 * C type : uint8_t[20]
	 */
	public byte[] pad0 = new byte[20];
	public xcb_get_image_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "depth", "sequence", "length", "visual", "pad0");
	}
	/**
	 * @param response_type <<br>
	 * @param depth <<br>
	 * @param sequence <<br>
	 * @param length <<br>
	 * @param visual <<br>
	 * C type : xcb_visualid_t<br>
	 * @param pad0 <<br>
	 * C type : uint8_t[20]
	 */
	public xcb_get_image_reply_t(byte response_type, byte depth, short sequence, int length, int visual, byte pad0[]) {
		super();
		this.response_type = response_type;
		this.depth = depth;
		this.sequence = sequence;
		this.length = length;
		this.visual = visual;
		if ((pad0.length != this.pad0.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad0 = pad0;
	}
	public xcb_get_image_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_get_image_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_get_image_reply_t implements Structure.ByValue {
		
	};
}
