package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:2654</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_alloc_color_planes_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte pad0;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/** < */
	public short pixels_len;
	/**
	 * <<br>
	 * C type : uint8_t[2]
	 */
	public byte[] pad1 = new byte[2];
	/** < */
	public int red_mask;
	/** < */
	public int green_mask;
	/** < */
	public int blue_mask;
	/**
	 * <<br>
	 * C type : uint8_t[8]
	 */
	public byte[] pad2 = new byte[8];
	public xcb_alloc_color_planes_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "pad0", "sequence", "length", "pixels_len", "pad1", "red_mask", "green_mask", "blue_mask", "pad2");
	}
	public xcb_alloc_color_planes_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_alloc_color_planes_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_alloc_color_planes_reply_t implements Structure.ByValue {
		
	};
}
