package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:3023</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_set_screen_saver_request_t extends Structure {
	/** < */
	public byte major_opcode;
	/** < */
	public byte pad0;
	/** < */
	public short length;
	/** < */
	public short timeout;
	/** < */
	public short interval;
	/** < */
	public byte prefer_blanking;
	/** < */
	public byte allow_exposures;
	public xcb_set_screen_saver_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("major_opcode", "pad0", "length", "timeout", "interval", "prefer_blanking", "allow_exposures");
	}
	/**
	 * @param major_opcode <<br>
	 * @param pad0 <<br>
	 * @param length <<br>
	 * @param timeout <<br>
	 * @param interval <<br>
	 * @param prefer_blanking <<br>
	 * @param allow_exposures <
	 */
	public xcb_set_screen_saver_request_t(byte major_opcode, byte pad0, short length, short timeout, short interval, byte prefer_blanking, byte allow_exposures) {
		super();
		this.major_opcode = major_opcode;
		this.pad0 = pad0;
		this.length = length;
		this.timeout = timeout;
		this.interval = interval;
		this.prefer_blanking = prefer_blanking;
		this.allow_exposures = allow_exposures;
	}
	public xcb_set_screen_saver_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_set_screen_saver_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_set_screen_saver_request_t implements Structure.ByValue {
		
	};
}
