package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xcb.h:51</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_ge_event_t extends Structure {
	/** < Type of the response */
	public byte response_type;
	/** < Padding */
	public byte pad0;
	/** < Sequence number */
	public short sequence;
	public int length;
	public short event_type;
	public short pad1;
	/**
	 * < Padding<br>
	 * C type : uint32_t[5]
	 */
	public int[] pad = new int[5];
	/** < full sequence */
	public int full_sequence;
	public xcb_ge_event_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "pad0", "sequence", "length", "event_type", "pad1", "pad", "full_sequence");
	}
	/**
	 * @param response_type < Type of the response<br>
	 * @param pad0 < Padding<br>
	 * @param sequence < Sequence number<br>
	 * @param pad < Padding<br>
	 * C type : uint32_t[5]<br>
	 * @param full_sequence < full sequence
	 */
	public xcb_ge_event_t(byte response_type, byte pad0, short sequence, int length, short event_type, short pad1, int pad[], int full_sequence) {
		super();
		this.response_type = response_type;
		this.pad0 = pad0;
		this.sequence = sequence;
		this.length = length;
		this.event_type = event_type;
		this.pad1 = pad1;
		if ((pad.length != this.pad.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad = pad;
		this.full_sequence = full_sequence;
	}
	public xcb_ge_event_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_ge_event_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_ge_event_t implements Structure.ByValue {
		
	};
}
