package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1678</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_timecoord_t extends Structure {
	/**
	 * <<br>
	 * C type : xcb_timestamp_t
	 */
	public int time;
	/** < */
	public short x;
	/** < */
	public short y;
	public xcb_timecoord_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("time", "x", "y");
	}
	/**
	 * @param time <<br>
	 * C type : xcb_timestamp_t<br>
	 * @param x <<br>
	 * @param y <
	 */
	public xcb_timecoord_t(int time, short x, short y) {
		super();
		this.time = time;
		this.x = x;
		this.y = y;
	}
	public xcb_timecoord_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_timecoord_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_timecoord_t implements Structure.ByValue {
		
	};
}
