package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xcb.h:9</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_auth_info_t extends Structure {
	/** < Length of the string name (as returned by strlen). */
	public int namelen;
	/**
	 * < String containing the authentication protocol name, such as "MIT-MAGIC-COOKIE-1" or "XDM-AUTHORIZATION-1".<br>
	 * C type : char*
	 */
	public Pointer name;
	/** < Length of the data member. */
	public int datalen;
	/**
	 * < Data interpreted in a protocol-specific manner.<br>
	 * C type : char*
	 */
	public Pointer data;
	public xcb_auth_info_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("namelen", "name", "datalen", "data");
	}
	/**
	 * @param namelen < Length of the string name (as returned by strlen).<br>
	 * @param name < String containing the authentication protocol name, such as "MIT-MAGIC-COOKIE-1" or "XDM-AUTHORIZATION-1".<br>
	 * C type : char*<br>
	 * @param datalen < Length of the data member.<br>
	 * @param data < Data interpreted in a protocol-specific manner.<br>
	 * C type : char*
	 */
	public xcb_auth_info_t(int namelen, Pointer name, int datalen, Pointer data) {
		super();
		this.namelen = namelen;
		this.name = name;
		this.datalen = datalen;
		this.data = data;
	}
	public xcb_auth_info_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_auth_info_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_auth_info_t implements Structure.ByValue {
		
	};
}
