package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1672</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_query_pointer_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte same_screen;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int root;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int child;
	/** < */
	public short root_x;
	/** < */
	public short root_y;
	/** < */
	public short win_x;
	/** < */
	public short win_y;
	/** < */
	public short mask;
	/**
	 * <<br>
	 * C type : uint8_t[2]
	 */
	public byte[] pad0 = new byte[2];
	public xcb_query_pointer_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "same_screen", "sequence", "length", "root", "child", "root_x", "root_y", "win_x", "win_y", "mask", "pad0");
	}
	public xcb_query_pointer_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_query_pointer_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_query_pointer_reply_t implements Structure.ByValue {
		
	};
}
