package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:155</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_format_t extends Structure {
	/** < */
	public byte depth;
	/** < */
	public byte bits_per_pixel;
	/** < */
	public byte scanline_pad;
	/**
	 * <<br>
	 * C type : uint8_t[5]
	 */
	public byte[] pad0 = new byte[5];
	public xcb_format_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("depth", "bits_per_pixel", "scanline_pad", "pad0");
	}
	/**
	 * @param depth <<br>
	 * @param bits_per_pixel <<br>
	 * @param scanline_pad <<br>
	 * @param pad0 <<br>
	 * C type : uint8_t[5]
	 */
	public xcb_format_t(byte depth, byte bits_per_pixel, byte scanline_pad, byte pad0[]) {
		super();
		this.depth = depth;
		this.bits_per_pixel = bits_per_pixel;
		this.scanline_pad = scanline_pad;
		if ((pad0.length != this.pad0.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad0 = pad0;
	}
	public xcb_format_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_format_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_format_t implements Structure.ByValue {
		
	};
}
