package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1786</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_get_input_focus_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte revert_to;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int focus;
	public xcb_get_input_focus_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "revert_to", "sequence", "length", "focus");
	}
	/**
	 * @param response_type <<br>
	 * @param revert_to <<br>
	 * @param sequence <<br>
	 * @param length <<br>
	 * @param focus <<br>
	 * C type : xcb_window_t
	 */
	public xcb_get_input_focus_reply_t(byte response_type, byte revert_to, short sequence, int length, int focus) {
		super();
		this.response_type = response_type;
		this.revert_to = revert_to;
		this.sequence = sequence;
		this.length = length;
		this.focus = focus;
	}
	public xcb_get_input_focus_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_get_input_focus_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_get_input_focus_reply_t implements Structure.ByValue {
		
	};
}
