package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:564</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_unmap_notify_event_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte pad0;
	/** < */
	public short sequence;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int event;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int window;
	/** < */
	public byte from_configure;
	/**
	 * <<br>
	 * C type : uint8_t[3]
	 */
	public byte[] pad1 = new byte[3];
	public xcb_unmap_notify_event_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "pad0", "sequence", "event", "window", "from_configure", "pad1");
	}
	/**
	 * @param response_type <<br>
	 * @param pad0 <<br>
	 * @param sequence <<br>
	 * @param event <<br>
	 * C type : xcb_window_t<br>
	 * @param window <<br>
	 * C type : xcb_window_t<br>
	 * @param from_configure <<br>
	 * @param pad1 <<br>
	 * C type : uint8_t[3]
	 */
	public xcb_unmap_notify_event_t(byte response_type, byte pad0, short sequence, int event, int window, byte from_configure, byte pad1[]) {
		super();
		this.response_type = response_type;
		this.pad0 = pad0;
		this.sequence = sequence;
		this.event = event;
		this.window = window;
		this.from_configure = from_configure;
		if ((pad1.length != this.pad1.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad1 = pad1;
	}
	public xcb_unmap_notify_event_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_unmap_notify_event_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_unmap_notify_event_t implements Structure.ByValue {
		
	};
}
