package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xcb.h:13</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_generic_iterator_t extends Structure {
	/**
	 * < Data of the current iterator<br>
	 * C type : void*
	 */
	public Pointer data;
	/** < remaining elements */
	public int rem;
	/** < index of the current iterator */
	public int index;
	public xcb_generic_iterator_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("data", "rem", "index");
	}
	/**
	 * @param data < Data of the current iterator<br>
	 * C type : void*<br>
	 * @param rem < remaining elements<br>
	 * @param index < index of the current iterator
	 */
	public xcb_generic_iterator_t(Pointer data, int rem, int index) {
		super();
		this.data = data;
		this.rem = rem;
		this.index = index;
	}
	public xcb_generic_iterator_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_generic_iterator_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_generic_iterator_t implements Structure.ByValue {
		
	};
}
