package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1090</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_get_window_attributes_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte backing_store;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/**
	 * <<br>
	 * C type : xcb_visualid_t
	 */
	public int visual;
	/** < */
	public short _class;
	/** < */
	public byte bit_gravity;
	/** < */
	public byte win_gravity;
	/** < */
	public int backing_planes;
	/** < */
	public int backing_pixel;
	/** < */
	public byte save_under;
	/** < */
	public byte map_is_installed;
	/** < */
	public byte map_state;
	/** < */
	public byte override_redirect;
	/**
	 * <<br>
	 * C type : xcb_colormap_t
	 */
	public int colormap;
	/** < */
	public int all_event_masks;
	/** < */
	public int your_event_mask;
	/** < */
	public short do_not_propagate_mask;
	/**
	 * <<br>
	 * C type : uint8_t[2]
	 */
	public byte[] pad0 = new byte[2];
	public xcb_get_window_attributes_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "backing_store", "sequence", "length", "visual", "_class", "bit_gravity", "win_gravity", "backing_planes", "backing_pixel", "save_under", "map_is_installed", "map_state", "override_redirect", "colormap", "all_event_masks", "your_event_mask", "do_not_propagate_mask", "pad0");
	}
	public xcb_get_window_attributes_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_get_window_attributes_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_get_window_attributes_reply_t implements Structure.ByValue {
		
	};
}
