package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:3096</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_list_hosts_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte mode;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/** < */
	public short hosts_len;
	/**
	 * <<br>
	 * C type : uint8_t[22]
	 */
	public byte[] pad0 = new byte[22];
	public xcb_list_hosts_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "mode", "sequence", "length", "hosts_len", "pad0");
	}
	/**
	 * @param response_type <<br>
	 * @param mode <<br>
	 * @param sequence <<br>
	 * @param length <<br>
	 * @param hosts_len <<br>
	 * @param pad0 <<br>
	 * C type : uint8_t[22]
	 */
	public xcb_list_hosts_reply_t(byte response_type, byte mode, short sequence, int length, short hosts_len, byte pad0[]) {
		super();
		this.response_type = response_type;
		this.mode = mode;
		this.sequence = sequence;
		this.length = length;
		this.hosts_len = hosts_len;
		if ((pad0.length != this.pad0.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad0 = pad0;
	}
	public xcb_list_hosts_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_list_hosts_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_list_hosts_reply_t implements Structure.ByValue {
		
	};
}
