package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:2616</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_alloc_color_cells_request_t extends Structure {
	/** < */
	public byte major_opcode;
	/** < */
	public byte contiguous;
	/** < */
	public short length;
	/**
	 * <<br>
	 * C type : xcb_colormap_t
	 */
	public int cmap;
	/** < */
	public short colors;
	/** < */
	public short planes;
	public xcb_alloc_color_cells_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("major_opcode", "contiguous", "length", "cmap", "colors", "planes");
	}
	/**
	 * @param major_opcode <<br>
	 * @param contiguous <<br>
	 * @param length <<br>
	 * @param cmap <<br>
	 * C type : xcb_colormap_t<br>
	 * @param colors <<br>
	 * @param planes <
	 */
	public xcb_alloc_color_cells_request_t(byte major_opcode, byte contiguous, short length, int cmap, short colors, short planes) {
		super();
		this.major_opcode = major_opcode;
		this.contiguous = contiguous;
		this.length = length;
		this.cmap = cmap;
		this.colors = colors;
		this.planes = planes;
	}
	public xcb_alloc_color_cells_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_alloc_color_cells_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_alloc_color_cells_request_t implements Structure.ByValue {
		
	};
}
