package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:293</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_setup_authenticate_t extends Structure {
	/** < */
	public byte status;
	/**
	 * <<br>
	 * C type : uint8_t[5]
	 */
	public byte[] pad0 = new byte[5];
	/** < */
	public short length;
	public xcb_setup_authenticate_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "pad0", "length");
	}
	/**
	 * @param status <<br>
	 * @param pad0 <<br>
	 * C type : uint8_t[5]<br>
	 * @param length <
	 */
	public xcb_setup_authenticate_t(byte status, byte pad0[], short length) {
		super();
		this.status = status;
		if ((pad0.length != this.pad0.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad0 = pad0;
		this.length = length;
	}
	public xcb_setup_authenticate_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_setup_authenticate_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_setup_authenticate_t implements Structure.ByValue {
		
	};
}
