package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:517</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_no_exposure_event_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte pad0;
	/** < */
	public short sequence;
	/**
	 * <<br>
	 * C type : xcb_drawable_t
	 */
	public int drawable;
	/** < */
	public short minor_opcode;
	/** < */
	public byte major_opcode;
	/** < */
	public byte pad1;
	public xcb_no_exposure_event_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "pad0", "sequence", "drawable", "minor_opcode", "major_opcode", "pad1");
	}
	/**
	 * @param response_type <<br>
	 * @param pad0 <<br>
	 * @param sequence <<br>
	 * @param drawable <<br>
	 * C type : xcb_drawable_t<br>
	 * @param minor_opcode <<br>
	 * @param major_opcode <<br>
	 * @param pad1 <
	 */
	public xcb_no_exposure_event_t(byte response_type, byte pad0, short sequence, int drawable, short minor_opcode, byte major_opcode, byte pad1) {
		super();
		this.response_type = response_type;
		this.pad0 = pad0;
		this.sequence = sequence;
		this.drawable = drawable;
		this.minor_opcode = minor_opcode;
		this.major_opcode = major_opcode;
		this.pad1 = pad1;
	}
	public xcb_no_exposure_event_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_no_exposure_event_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_no_exposure_event_t implements Structure.ByValue {
		
	};
}
