package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:2422</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_put_image_request_t extends Structure {
	/** < */
	public byte major_opcode;
	/** < */
	public byte format;
	/** < */
	public short length;
	/**
	 * <<br>
	 * C type : xcb_drawable_t
	 */
	public int drawable;
	/**
	 * <<br>
	 * C type : xcb_gcontext_t
	 */
	public int gc;
	/** < */
	public short width;
	/** < */
	public short height;
	/** < */
	public short dst_x;
	/** < */
	public short dst_y;
	/** < */
	public byte left_pad;
	/** < */
	public byte depth;
	/**
	 * <<br>
	 * C type : uint8_t[2]
	 */
	public byte[] pad0 = new byte[2];
	public xcb_put_image_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("major_opcode", "format", "length", "drawable", "gc", "width", "height", "dst_x", "dst_y", "left_pad", "depth", "pad0");
	}
	public xcb_put_image_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_put_image_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_put_image_request_t implements Structure.ByValue {
		
	};
}
