package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:281</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_setup_failed_t extends Structure {
	/** < */
	public byte status;
	/** < */
	public byte reason_len;
	/** < */
	public short protocol_major_version;
	/** < */
	public short protocol_minor_version;
	/** < */
	public short length;
	public xcb_setup_failed_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "reason_len", "protocol_major_version", "protocol_minor_version", "length");
	}
	/**
	 * @param status <<br>
	 * @param reason_len <<br>
	 * @param protocol_major_version <<br>
	 * @param protocol_minor_version <<br>
	 * @param length <
	 */
	public xcb_setup_failed_t(byte status, byte reason_len, short protocol_major_version, short protocol_minor_version, short length) {
		super();
		this.status = status;
		this.reason_len = reason_len;
		this.protocol_major_version = protocol_major_version;
		this.protocol_minor_version = protocol_minor_version;
		this.length = length;
	}
	public xcb_setup_failed_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_setup_failed_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_setup_failed_t implements Structure.ByValue {
		
	};
}
