package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:251</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_screen_t extends Structure {
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int root;
	/**
	 * <<br>
	 * C type : xcb_colormap_t
	 */
	public int default_colormap;
	/** < */
	public int white_pixel;
	/** < */
	public int black_pixel;
	/** < */
	public int current_input_masks;
	/** < */
	public short width_in_pixels;
	/** < */
	public short height_in_pixels;
	/** < */
	public short width_in_millimeters;
	/** < */
	public short height_in_millimeters;
	/** < */
	public short min_installed_maps;
	/** < */
	public short max_installed_maps;
	/**
	 * <<br>
	 * C type : xcb_visualid_t
	 */
	public int root_visual;
	/** < */
	public byte backing_stores;
	/** < */
	public byte save_unders;
	/** < */
	public byte root_depth;
	/** < */
	public byte allowed_depths_len;
	public xcb_screen_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("root", "default_colormap", "white_pixel", "black_pixel", "current_input_masks", "width_in_pixels", "height_in_pixels", "width_in_millimeters", "height_in_millimeters", "min_installed_maps", "max_installed_maps", "root_visual", "backing_stores", "save_unders", "root_depth", "allowed_depths_len");
	}
	public xcb_screen_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_screen_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_screen_t implements Structure.ByValue {
		
	};
}
