package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1299</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_change_property_request_t extends Structure {
	/** < */
	public byte major_opcode;
	/** < */
	public byte mode;
	/** < */
	public short length;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int window;
	/**
	 * <<br>
	 * C type : xcb_atom_t
	 */
	public int property;
	/**
	 * <<br>
	 * C type : xcb_atom_t
	 */
	public int type;
	/** < */
	public byte format;
	/**
	 * <<br>
	 * C type : uint8_t[3]
	 */
	public byte[] pad0 = new byte[3];
	/** < */
	public int data_len;
	public xcb_change_property_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("major_opcode", "mode", "length", "window", "property", "type", "format", "pad0", "data_len");
	}
	/**
	 * @param major_opcode <<br>
	 * @param mode <<br>
	 * @param length <<br>
	 * @param window <<br>
	 * C type : xcb_window_t<br>
	 * @param property <<br>
	 * C type : xcb_atom_t<br>
	 * @param type <<br>
	 * C type : xcb_atom_t<br>
	 * @param format <<br>
	 * @param pad0 <<br>
	 * C type : uint8_t[3]<br>
	 * @param data_len <
	 */
	public xcb_change_property_request_t(byte major_opcode, byte mode, short length, int window, int property, int type, byte format, byte pad0[], int data_len) {
		super();
		this.major_opcode = major_opcode;
		this.mode = mode;
		this.length = length;
		this.window = window;
		this.property = property;
		this.type = type;
		this.format = format;
		if ((pad0.length != this.pad0.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad0 = pad0;
		this.data_len = data_len;
	}
	public xcb_change_property_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_change_property_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_change_property_request_t implements Structure.ByValue {
		
	};
}
