package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:2845</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_query_best_size_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte pad0;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/** < */
	public short width;
	/** < */
	public short height;
	public xcb_query_best_size_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "pad0", "sequence", "length", "width", "height");
	}
	/**
	 * @param response_type <<br>
	 * @param pad0 <<br>
	 * @param sequence <<br>
	 * @param length <<br>
	 * @param width <<br>
	 * @param height <
	 */
	public xcb_query_best_size_reply_t(byte response_type, byte pad0, short sequence, int length, short width, short height) {
		super();
		this.response_type = response_type;
		this.pad0 = pad0;
		this.sequence = sequence;
		this.length = length;
		this.width = width;
		this.height = height;
	}
	public xcb_query_best_size_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_query_best_size_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_query_best_size_reply_t implements Structure.ByValue {
		
	};
}
