package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1325</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_get_property_request_t extends Structure {
	/** < */
	public byte major_opcode;
	/** < */
	public byte _delete;
	/** < */
	public short length;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int window;
	/**
	 * <<br>
	 * C type : xcb_atom_t
	 */
	public int property;
	/**
	 * <<br>
	 * C type : xcb_atom_t
	 */
	public int type;
	/** < */
	public int long_offset;
	/** < */
	public int long_length;
	public xcb_get_property_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("major_opcode", "_delete", "length", "window", "property", "type", "long_offset", "long_length");
	}
	/**
	 * @param major_opcode <<br>
	 * @param _delete <<br>
	 * @param length <<br>
	 * @param window <<br>
	 * C type : xcb_window_t<br>
	 * @param property <<br>
	 * C type : xcb_atom_t<br>
	 * @param type <<br>
	 * C type : xcb_atom_t<br>
	 * @param long_offset <<br>
	 * @param long_length <
	 */
	public xcb_get_property_request_t(byte major_opcode, byte _delete, short length, int window, int property, int type, int long_offset, int long_length) {
		super();
		this.major_opcode = major_opcode;
		this._delete = _delete;
		this.length = length;
		this.window = window;
		this.property = property;
		this.type = type;
		this.long_offset = long_offset;
		this.long_length = long_length;
	}
	public xcb_get_property_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_get_property_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_get_property_request_t implements Structure.ByValue {
		
	};
}
