package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:2758</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_lookup_color_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte pad0;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/** < */
	public short exact_red;
	/** < */
	public short exact_green;
	/** < */
	public short exact_blue;
	/** < */
	public short visual_red;
	/** < */
	public short visual_green;
	/** < */
	public short visual_blue;
	public xcb_lookup_color_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "pad0", "sequence", "length", "exact_red", "exact_green", "exact_blue", "visual_red", "visual_green", "visual_blue");
	}
	public xcb_lookup_color_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_lookup_color_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_lookup_color_reply_t implements Structure.ByValue {
		
	};
}
