package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:2312</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_copy_plane_request_t extends Structure {
	/** < */
	public byte major_opcode;
	/** < */
	public byte pad0;
	/** < */
	public short length;
	/**
	 * <<br>
	 * C type : xcb_drawable_t
	 */
	public int src_drawable;
	/**
	 * <<br>
	 * C type : xcb_drawable_t
	 */
	public int dst_drawable;
	/**
	 * <<br>
	 * C type : xcb_gcontext_t
	 */
	public int gc;
	/** < */
	public short src_x;
	/** < */
	public short src_y;
	/** < */
	public short dst_x;
	/** < */
	public short dst_y;
	/** < */
	public short width;
	/** < */
	public short height;
	/** < */
	public int bit_plane;
	public xcb_copy_plane_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("major_opcode", "pad0", "length", "src_drawable", "dst_drawable", "gc", "src_x", "src_y", "dst_x", "dst_y", "width", "height", "bit_plane");
	}
	public xcb_copy_plane_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_copy_plane_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_copy_plane_request_t implements Structure.ByValue {
		
	};
}
