package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:479</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_keymap_notify_event_t extends Structure {
	/** < */
	public byte response_type;
	/**
	 * <<br>
	 * C type : uint8_t[31]
	 */
	public byte[] keys = new byte[31];
	public xcb_keymap_notify_event_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "keys");
	}
	/**
	 * @param response_type <<br>
	 * @param keys <<br>
	 * C type : uint8_t[31]
	 */
	public xcb_keymap_notify_event_t(byte response_type, byte keys[]) {
		super();
		this.response_type = response_type;
		if ((keys.length != this.keys.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.keys = keys;
	}
	public xcb_keymap_notify_event_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_keymap_notify_event_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_keymap_notify_event_t implements Structure.ByValue {
		
	};
}
