package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:2818</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_recolor_cursor_request_t extends Structure {
	/** < */
	public byte major_opcode;
	/** < */
	public byte pad0;
	/** < */
	public short length;
	/**
	 * <<br>
	 * C type : xcb_cursor_t
	 */
	public int cursor;
	/** < */
	public short fore_red;
	/** < */
	public short fore_green;
	/** < */
	public short fore_blue;
	/** < */
	public short back_red;
	/** < */
	public short back_green;
	/** < */
	public short back_blue;
	public xcb_recolor_cursor_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("major_opcode", "pad0", "length", "cursor", "fore_red", "fore_green", "fore_blue", "back_red", "back_green", "back_blue");
	}
	public xcb_recolor_cursor_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_recolor_cursor_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_recolor_cursor_request_t implements Structure.ByValue {
		
	};
}
