package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:2340</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_segment_t extends Structure {
	/** < */
	public short x1;
	/** < */
	public short y1;
	/** < */
	public short x2;
	/** < */
	public short y2;
	public xcb_segment_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("x1", "y1", "x2", "y2");
	}
	/**
	 * @param x1 <<br>
	 * @param y1 <<br>
	 * @param x2 <<br>
	 * @param y2 <
	 */
	public xcb_segment_t(short x1, short y1, short x2, short y2) {
		super();
		this.x1 = x1;
		this.y1 = y1;
		this.x2 = x2;
		this.y2 = y2;
	}
	public xcb_segment_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_segment_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_segment_t implements Structure.ByValue {
		
	};
}
