package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1444</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_grab_pointer_request_t extends Structure {
	/** < */
	public byte major_opcode;
	/** < */
	public byte owner_events;
	/** < */
	public short length;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int grab_window;
	/** < */
	public short event_mask;
	/** < */
	public byte pointer_mode;
	/** < */
	public byte keyboard_mode;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int confine_to;
	/**
	 * <<br>
	 * C type : xcb_cursor_t
	 */
	public int cursor;
	/**
	 * <<br>
	 * C type : xcb_timestamp_t
	 */
	public int time;
	public xcb_grab_pointer_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("major_opcode", "owner_events", "length", "grab_window", "event_mask", "pointer_mode", "keyboard_mode", "confine_to", "cursor", "time");
	}
	public xcb_grab_pointer_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_grab_pointer_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_grab_pointer_request_t implements Structure.ByValue {
		
	};
}
