package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:626</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_configure_request_event_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte stack_mode;
	/** < */
	public short sequence;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int parent;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int window;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int sibling;
	/** < */
	public short x;
	/** < */
	public short y;
	/** < */
	public short width;
	/** < */
	public short height;
	/** < */
	public short border_width;
	/** < */
	public short value_mask;
	public xcb_configure_request_event_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "stack_mode", "sequence", "parent", "window", "sibling", "x", "y", "width", "height", "border_width", "value_mask");
	}
	public xcb_configure_request_event_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_configure_request_event_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_configure_request_event_t implements Structure.ByValue {
		
	};
}
