package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:5</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_char2b_t extends Structure {
	/** < */
	public byte byte1;
	/** < */
	public byte byte2;
	public xcb_char2b_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("byte1", "byte2");
	}
	/**
	 * @param byte1 <<br>
	 * @param byte2 <
	 */
	public xcb_char2b_t(byte byte1, byte byte2) {
		super();
		this.byte1 = byte1;
		this.byte2 = byte2;
	}
	public xcb_char2b_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_char2b_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_char2b_t implements Structure.ByValue {
		
	};
}
