package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:2576</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_alloc_color_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte pad0;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/** < */
	public short red;
	/** < */
	public short green;
	/** < */
	public short blue;
	/**
	 * <<br>
	 * C type : uint8_t[2]
	 */
	public byte[] pad1 = new byte[2];
	/** < */
	public int pixel;
	public xcb_alloc_color_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "pad0", "sequence", "length", "red", "green", "blue", "pad1", "pixel");
	}
	/**
	 * @param response_type <<br>
	 * @param pad0 <<br>
	 * @param sequence <<br>
	 * @param length <<br>
	 * @param red <<br>
	 * @param green <<br>
	 * @param blue <<br>
	 * @param pad1 <<br>
	 * C type : uint8_t[2]<br>
	 * @param pixel <
	 */
	public xcb_alloc_color_reply_t(byte response_type, byte pad0, short sequence, int length, short red, short green, short blue, byte pad1[], int pixel) {
		super();
		this.response_type = response_type;
		this.pad0 = pad0;
		this.sequence = sequence;
		this.length = length;
		this.red = red;
		this.green = green;
		this.blue = blue;
		if ((pad1.length != this.pad1.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad1 = pad1;
		this.pixel = pixel;
	}
	public xcb_alloc_color_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_alloc_color_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_alloc_color_reply_t implements Structure.ByValue {
		
	};
}
