package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:326</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_setup_t extends Structure {
	/** < */
	public byte status;
	/** < */
	public byte pad0;
	/** < */
	public short protocol_major_version;
	/** < */
	public short protocol_minor_version;
	/** < */
	public short length;
	/** < */
	public int release_number;
	/** < */
	public int resource_id_base;
	/** < */
	public int resource_id_mask;
	/** < */
	public int motion_buffer_size;
	/** < */
	public short vendor_len;
	/** < */
	public short maximum_request_length;
	/** < */
	public byte roots_len;
	/** < */
	public byte pixmap_formats_len;
	/** < */
	public byte image_byte_order;
	/** < */
	public byte bitmap_format_bit_order;
	/** < */
	public byte bitmap_format_scanline_unit;
	/** < */
	public byte bitmap_format_scanline_pad;
	/**
	 * <<br>
	 * C type : xcb_keycode_t
	 */
	public byte min_keycode;
	/**
	 * <<br>
	 * C type : xcb_keycode_t
	 */
	public byte max_keycode;
	/**
	 * <<br>
	 * C type : uint8_t[4]
	 */
	public byte[] pad1 = new byte[4];
	public xcb_setup_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "pad0", "protocol_major_version", "protocol_minor_version", "length", "release_number", "resource_id_base", "resource_id_mask", "motion_buffer_size", "vendor_len", "maximum_request_length", "roots_len", "pixmap_formats_len", "image_byte_order", "bitmap_format_bit_order", "bitmap_format_scanline_unit", "bitmap_format_scanline_pad", "min_keycode", "max_keycode", "pad1");
	}
	public xcb_setup_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_setup_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_setup_t implements Structure.ByValue {
		
	};
}
