package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * <i>native declaration : xcb/xproto.h:810</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_client_message_data_t extends Union {
	/**
	 * <<br>
	 * C type : uint8_t[20]
	 */
	public byte[] data8 = new byte[20];
	/**
	 * <<br>
	 * C type : uint16_t[10]
	 */
	public short[] data16 = new short[10];
	/**
	 * <<br>
	 * C type : uint32_t[5]
	 */
	public int[] data32 = new int[5];
	public xcb_client_message_data_t() {
		super();
	}
	/**
	 * @param data8 <<br>
	 * C type : uint8_t[20]
	 */
	public xcb_client_message_data_t(byte data8[]) {
		super();
		if ((data8.length != this.data8.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.data8 = data8;
		setType(byte[].class);
	}
	/**
	 * @param data16 <<br>
	 * C type : uint16_t[10]
	 */
	public xcb_client_message_data_t(short data16[]) {
		super();
		if ((data16.length != this.data16.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.data16 = data16;
		setType(short[].class);
	}
	/**
	 * @param data32 <<br>
	 * C type : uint32_t[5]
	 */
	public xcb_client_message_data_t(int data32[]) {
		super();
		if ((data32.length != this.data32.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.data32 = data32;
		setType(int[].class);
	}
	public xcb_client_message_data_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_client_message_data_t implements com.sun.jna.Structure.ByReference {
		
	};
	public static class ByValue extends xcb_client_message_data_t implements com.sun.jna.Structure.ByValue {
		
	};
}
