package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:267</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_setup_request_t extends Structure {
	/** < */
	public byte byte_order;
	/** < */
	public byte pad0;
	/** < */
	public short protocol_major_version;
	/** < */
	public short protocol_minor_version;
	/** < */
	public short authorization_protocol_name_len;
	/** < */
	public short authorization_protocol_data_len;
	/**
	 * <<br>
	 * C type : uint8_t[2]
	 */
	public byte[] pad1 = new byte[2];
	public xcb_setup_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("byte_order", "pad0", "protocol_major_version", "protocol_minor_version", "authorization_protocol_name_len", "authorization_protocol_data_len", "pad1");
	}
	/**
	 * @param byte_order <<br>
	 * @param pad0 <<br>
	 * @param protocol_major_version <<br>
	 * @param protocol_minor_version <<br>
	 * @param authorization_protocol_name_len <<br>
	 * @param authorization_protocol_data_len <<br>
	 * @param pad1 <<br>
	 * C type : uint8_t[2]
	 */
	public xcb_setup_request_t(byte byte_order, byte pad0, short protocol_major_version, short protocol_minor_version, short authorization_protocol_name_len, short authorization_protocol_data_len, byte pad1[]) {
		super();
		this.byte_order = byte_order;
		this.pad0 = pad0;
		this.protocol_major_version = protocol_major_version;
		this.protocol_minor_version = protocol_minor_version;
		this.authorization_protocol_name_len = authorization_protocol_name_len;
		this.authorization_protocol_data_len = authorization_protocol_data_len;
		if ((pad1.length != this.pad1.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad1 = pad1;
	}
	public xcb_setup_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_setup_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_setup_request_t implements Structure.ByValue {
		
	};
}
