package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1883</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_query_font_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte pad0;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/**
	 * <<br>
	 * C type : xcb_charinfo_t
	 */
	public xcb_charinfo_t min_bounds;
	/**
	 * <<br>
	 * C type : uint8_t[4]
	 */
	public byte[] pad1 = new byte[4];
	/**
	 * <<br>
	 * C type : xcb_charinfo_t
	 */
	public xcb_charinfo_t max_bounds;
	/**
	 * <<br>
	 * C type : uint8_t[4]
	 */
	public byte[] pad2 = new byte[4];
	/** < */
	public short min_char_or_byte2;
	/** < */
	public short max_char_or_byte2;
	/** < */
	public short default_char;
	/** < */
	public short properties_len;
	/** < */
	public byte draw_direction;
	/** < */
	public byte min_byte1;
	/** < */
	public byte max_byte1;
	/** < */
	public byte all_chars_exist;
	/** < */
	public short font_ascent;
	/** < */
	public short font_descent;
	/** < */
	public int char_infos_len;
	public xcb_query_font_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "pad0", "sequence", "length", "min_bounds", "pad1", "max_bounds", "pad2", "min_char_or_byte2", "max_char_or_byte2", "default_char", "properties_len", "draw_direction", "min_byte1", "max_byte1", "all_chars_exist", "font_ascent", "font_descent", "char_infos_len");
	}
	public xcb_query_font_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_query_font_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_query_font_reply_t implements Structure.ByValue {
		
	};
}
