package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1908</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_query_text_extents_reply_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte draw_direction;
	/** < */
	public short sequence;
	/** < */
	public int length;
	/** < */
	public short font_ascent;
	/** < */
	public short font_descent;
	/** < */
	public short overall_ascent;
	/** < */
	public short overall_descent;
	/** < */
	public int overall_width;
	/** < */
	public int overall_left;
	/** < */
	public int overall_right;
	public xcb_query_text_extents_reply_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "draw_direction", "sequence", "length", "font_ascent", "font_descent", "overall_ascent", "overall_descent", "overall_width", "overall_left", "overall_right");
	}
	public xcb_query_text_extents_reply_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_query_text_extents_reply_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_query_text_extents_reply_t implements Structure.ByValue {
		
	};
}
