package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:636</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_gravity_notify_event_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte pad0;
	/** < */
	public short sequence;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int event;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int window;
	/** < */
	public short x;
	/** < */
	public short y;
	public xcb_gravity_notify_event_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "pad0", "sequence", "event", "window", "x", "y");
	}
	/**
	 * @param response_type <<br>
	 * @param pad0 <<br>
	 * @param sequence <<br>
	 * @param event <<br>
	 * C type : xcb_window_t<br>
	 * @param window <<br>
	 * C type : xcb_window_t<br>
	 * @param x <<br>
	 * @param y <
	 */
	public xcb_gravity_notify_event_t(byte response_type, byte pad0, short sequence, int event, int window, short x, short y) {
		super();
		this.response_type = response_type;
		this.pad0 = pad0;
		this.sequence = sequence;
		this.event = event;
		this.window = window;
		this.x = x;
		this.y = y;
	}
	public xcb_gravity_notify_event_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_gravity_notify_event_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_gravity_notify_event_t implements Structure.ByValue {
		
	};
}
