package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1829</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_fontprop_t extends Structure {
	/**
	 * <<br>
	 * C type : xcb_atom_t
	 */
	public int name;
	/** < */
	public int value;
	public xcb_fontprop_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("name", "value");
	}
	/**
	 * @param name <<br>
	 * C type : xcb_atom_t<br>
	 * @param value <
	 */
	public xcb_fontprop_t(int name, int value) {
		super();
		this.name = name;
		this.value = value;
	}
	public xcb_fontprop_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_fontprop_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_fontprop_t implements Structure.ByValue {
		
	};
}
