package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:840</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_mapping_notify_event_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte pad0;
	/** < */
	public short sequence;
	/** < */
	public byte request;
	/**
	 * <<br>
	 * C type : xcb_keycode_t
	 */
	public byte first_keycode;
	/** < */
	public byte count;
	/** < */
	public byte pad1;
	public xcb_mapping_notify_event_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "pad0", "sequence", "request", "first_keycode", "count", "pad1");
	}
	/**
	 * @param response_type <<br>
	 * @param pad0 <<br>
	 * @param sequence <<br>
	 * @param request <<br>
	 * @param first_keycode <<br>
	 * C type : xcb_keycode_t<br>
	 * @param count <<br>
	 * @param pad1 <
	 */
	public xcb_mapping_notify_event_t(byte response_type, byte pad0, short sequence, byte request, byte first_keycode, byte count, byte pad1) {
		super();
		this.response_type = response_type;
		this.pad0 = pad0;
		this.sequence = sequence;
		this.request = request;
		this.first_keycode = first_keycode;
		this.count = count;
		this.pad1 = pad1;
	}
	public xcb_mapping_notify_event_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_mapping_notify_event_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_mapping_notify_event_t implements Structure.ByValue {
		
	};
}
