package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:180</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_visualtype_t extends Structure {
	/**
	 * <<br>
	 * C type : xcb_visualid_t
	 */
	public int visual_id;
	/** < */
	public byte _class;
	/** < */
	public byte bits_per_rgb_value;
	/** < */
	public short colormap_entries;
	/** < */
	public int red_mask;
	/** < */
	public int green_mask;
	/** < */
	public int blue_mask;
	/**
	 * <<br>
	 * C type : uint8_t[4]
	 */
	public byte[] pad0 = new byte[4];
	public xcb_visualtype_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("visual_id", "_class", "bits_per_rgb_value", "colormap_entries", "red_mask", "green_mask", "blue_mask", "pad0");
	}
	/**
	 * @param visual_id <<br>
	 * C type : xcb_visualid_t<br>
	 * @param _class <<br>
	 * @param bits_per_rgb_value <<br>
	 * @param colormap_entries <<br>
	 * @param red_mask <<br>
	 * @param green_mask <<br>
	 * @param blue_mask <<br>
	 * @param pad0 <<br>
	 * C type : uint8_t[4]
	 */
	public xcb_visualtype_t(int visual_id, byte _class, byte bits_per_rgb_value, short colormap_entries, int red_mask, int green_mask, int blue_mask, byte pad0[]) {
		super();
		this.visual_id = visual_id;
		this._class = _class;
		this.bits_per_rgb_value = bits_per_rgb_value;
		this.colormap_entries = colormap_entries;
		this.red_mask = red_mask;
		this.green_mask = green_mask;
		this.blue_mask = blue_mask;
		if ((pad0.length != this.pad0.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad0 = pad0;
	}
	public xcb_visualtype_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_visualtype_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_visualtype_t implements Structure.ByValue {
		
	};
}
