package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:825</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_client_message_event_t extends Structure {
	/** < */
	public byte response_type;
	/** < */
	public byte format;
	/** < */
	public short sequence;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int window;
	/**
	 * <<br>
	 * C type : xcb_atom_t
	 */
	public int type;
	/**
	 * <<br>
	 * C type : xcb_client_message_data_t
	 */
	public xcb_client_message_data_t data;
	public xcb_client_message_event_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("response_type", "format", "sequence", "window", "type", "data");
	}
	/**
	 * @param response_type <<br>
	 * @param format <<br>
	 * @param sequence <<br>
	 * @param window <<br>
	 * C type : xcb_window_t<br>
	 * @param type <<br>
	 * C type : xcb_atom_t<br>
	 * @param data <<br>
	 * C type : xcb_client_message_data_t
	 */
	public xcb_client_message_event_t(byte response_type, byte format, short sequence, int window, int type, xcb_client_message_data_t data) {
		super();
		this.response_type = response_type;
		this.format = format;
		this.sequence = sequence;
		this.window = window;
		this.type = type;
		this.data = data;
	}
	public xcb_client_message_event_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_client_message_event_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_client_message_event_t implements Structure.ByValue {
		
	};
}
