package xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : xcb/xproto.h:1408</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_send_event_request_t extends Structure {
	/** < */
	public byte major_opcode;
	/** < */
	public byte propagate;
	/** < */
	public short length;
	/**
	 * <<br>
	 * C type : xcb_window_t
	 */
	public int destination;
	/** < */
	public int event_mask;
	/**
	 * <<br>
	 * C type : char[32]
	 */
	public byte[] event = new byte[32];
	public xcb_send_event_request_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("major_opcode", "propagate", "length", "destination", "event_mask", "event");
	}
	/**
	 * @param major_opcode <<br>
	 * @param propagate <<br>
	 * @param length <<br>
	 * @param destination <<br>
	 * C type : xcb_window_t<br>
	 * @param event_mask <<br>
	 * @param event <<br>
	 * C type : char[32]
	 */
	public xcb_send_event_request_t(byte major_opcode, byte propagate, short length, int destination, int event_mask, byte event[]) {
		super();
		this.major_opcode = major_opcode;
		this.propagate = propagate;
		this.length = length;
		this.destination = destination;
		this.event_mask = event_mask;
		if ((event.length != this.event.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.event = event;
	}
	public xcb_send_event_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_send_event_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_send_event_request_t implements Structure.ByValue {
		
	};
}
